### ISSUE TITLE
userInfo에서 사용자 추가 및 삭제 시 daytable과의 갱신

### ISSUE THREAD

**Issue by GulSam00** [saveme-cadet/LMS-BE#13]
userInfo에서 유저 추가 시 dayTable에 반영이 되지 않아서 출결표에서 api/alltable/day로 가져올 때 에러가 나와 버린다.
attendStatus를 0으로 바꿔놓으면 api/alltable/day을 요청할 때 해당 유저를 가져오지 않지만 12시가 지나도 dayTable이 생성되지 않아 버린다.

* userInfo에서 유저 추가 시 그 당일에 해당하는 dayTable이 추가되어야 한다.

**Comment by jin-sungdae** [comment]
user 삭제 api 만들 었습니다. 
user Id로 삭제시키면 user 가 참조하고있던 userinfo, daytable, todo 가 삭제됩니다.
