### ISSUE TITLE
/api​/alltable​/day 요청 시 에러 핸들링

### ISSUE THREAD

**Issue by GulSam00** [saveme-cadet/LMS-BE#14]
기존에는 쿼리에 들어간 날짜와 userInfo에 등록된 유저 중 유저는 있는데 daytable이 없을 때 에러를 리턴했다.
존재하지 않는 daytable에 대해서는 제외하고 응답하도록 수정이 필요하다.

**Comment by jin-sungdae** [comment]
user 생성 시 당일날 부터 daytable 생성 되도록 api 수정 했습니다.
이제 user 생성 시키면 userInfo, userDayTable 이 db도 생성 됩니다.
