### ISSUE TITLE
​/api​/user​ API

### ISSUE THREAD

**Issue by GulSam00** [saveme-cadet/LMS-BE#35]
* [스웨거 문서](http://15.165.148.236:8080/swagger-ui/index.html?configUrl=/api-docs/swagger-config#/)에 등록된 API로 삭제 요청을 했는데 Bad Request가 발생했습니다. 확인 부탁드립니다.
* 유저 생성 API인 /api/usermake/sign-up가 ​/api​/user로 이동해도 될 것 같습니다.

**Comment by jin-sungdae** [comment]
이슈  확인했습니다
