### ISSUE TITLE
[Feature request] userInfo 수정 시 당일 daytable이 변경 필요

### ISSUE THREAD

**Issue by GulSam00** [saveme-cadet/LMS-BE#54]
attendStatus는 즉각 반영 되지만 team, role 등도 즉각 반영되어야 할 것 같습니다.

**Comment by jin-sungdae** [comment]
- API 제작 

### Put API

### API PATH
- /api/userinfo/teamandrole 
- user의 team 과 role 변경시 그 달의 전체 team 과 role 변경
