### ISSUE TITLE
[Bug report]  ​/api​/login 에러

### ISSUE THREAD

**Issue by GulSam00** [saveme-cadet/LMS-BE#58]
![error1](https://user-images.githubusercontent.com/72376700/161220273-8fd1f790-a57b-4b69-9c1b-1f2f715fcdb7.PNG)
아이디, 비밀번호를 올바르게 입력하였는데 500 에러가 발생했습니다. 확인 부탁드려요.

**Comment by jin-sungdae** [comment]
확인했습니다
