### ISSUE TITLE
[Feature request] 유저 초기값 재설정

### ISSUE THREAD

**Issue by GulSam00** [saveme-cadet/LMS-BE#60]
attendScore: 0
attendeStatus: 1
confidenceSubject: "뭘 까?" -> ""
level: 0
nowSubject: "뭘 까?" -> ""
participateScore: 0
role: "카 뎃" -> "카뎃"
team: "흰 색" -> "white"
userId: 4
userName: "aaa"
이렇게 수정되면 좋겠습니다!

**Comment by jin-sungdae** [comment]
수정 완료했습니다.
