### ISSUE TITLE
새로 만들어지는 dayTable의 participateScore, attendScore가 갱신되지 않음.

### ISSUE THREAD

**Issue by GulSam00** [saveme-cadet/LMS-BE#8]
<img width="1113" alt="Screen Shot 2022-03-07 at 12 04 53 PM" src="https://user-images.githubusercontent.com/72376700/156961025-fb9bc8bc-2cb6-4ec0-b078-3d30f273a523.png">
체크인, 체크아웃 API를 보내야만 그제서야 최신의 값을 갱신합니다.

**Comment by jin-sungdae** [comment]
수정 완료했습니다.
